import 'styles/globals.css';

import PropTypes from 'prop-types';
import { UserProvider } from '@auth0/nextjs-auth0';
import Layout from 'components/Layout';
import { ThemeProvider, CssBaseline } from '@material-ui/core';
import Head from 'next/head';
import theme from 'defaultTheme';

function MyApp({ Component, pageProps }) {
  if (typeof window === 'undefined') {
    return (
      <ThemeProvider theme={theme}>
        <CssBaseline />
      </ThemeProvider>
    );
  }
  return (
    <UserProvider>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <Head>
          <title>Ortho Panel</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </ThemeProvider>
    </UserProvider>
  );
}

MyApp.propTypes = {
  Component: PropTypes.func,
  pageProps: PropTypes.shape({}),
};

MyApp.defaultProps = {
  Component: null,
  pageProps: {},
};

export default MyApp;
