import 'styles/globals.css';

import PropTypes from 'prop-types';
import { UserProvider } from '@auth0/nextjs-auth0';
import Layout from 'components/Layout';
import { ThemeProvider, CssBaseline } from '@material-ui/core';
import Head from 'next/head';
import theme from 'defaultTheme';
import { ApolloProvider } from '@apollo/client';
import { useApollo } from 'lib/apollo-client';
import ClientOnly from 'components/ClientOnly';

function MyApp({ Component, pageProps }) {
  const apolloClient = useApollo(pageProps.initialApolloState);

  if (typeof window === 'undefined') {
    return (
      <ThemeProvider theme={theme}>
        <CssBaseline />
      </ThemeProvider>
    );
  }

  return (
    <UserProvider>
      <ApolloProvider client={apolloClient}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Head>
            <title>Ortho Panel</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Layout>
            <ClientOnly>
              <Component {...pageProps} />
            </ClientOnly>
          </Layout>
        </ThemeProvider>
      </ApolloProvider>
    </UserProvider>
  );
}

MyApp.propTypes = {
  Component: PropTypes.func,
  pageProps: PropTypes.shape({ initialApolloState: {} }),
};

MyApp.defaultProps = {
  Component: null,
  pageProps: {
    initialApolloState: {},
  },
};

export default MyApp;
